version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: 'task-image'
        container_name: task-php
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-shouts
        depends_on:
            - mysql
    mysql:
        image: 'mariadb:latest'
        container_name: task-db
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel-shouts
networks:
    laravel-shouts:
        driver: bridge
